#!/bin/sh

# lint — Linter for Webmachine

# Webmachine (https://github.com/melusina-org/cl-webmachine)
# This file is part of Webmachine.
#
# Copyright © 2018–2023 Michaël Le Barbier
# All rights reserved.

# This file must be used under the terms of the MIT License.
# This source file is licensed as described in the file LICENSE, which
# you should have received as part of this distribution. The terms
# are also available at https://opensource.org/licenses/MIT

: ${TOPLEVELDIR:=$(git rev-parse --show-toplevel)}
: ${lintsystem:="org.melusina.webmachine/development"}

lint_sbcl()
{
    sbcl --noinform --disable-debugger "$@"
}

lint_main()
{
    lint_sbcl --eval "(ql:quickload \"${lintsystem}\" :silent t)"\
	      --eval "(${lintsystem}:lint)"\
	      --quit
}

lint_main "$@"

# End of file `lint'
